### ISSUE TITLE
Performance needs to be improved

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#105]
I have done two movies below with the same Filterpane but feature flag on and off so Old and new. There is a huge difference in performance. The old is very responsive and fast while the new is not. You get the feeling that "did I click or not"?

OLD:
![abc!](https://user-images.githubusercontent.com/29114032/223050713-dfd500f6-4ee2-47e1-be81-0207a686fb0f.gif)

NEW:
 ![abc!](https://user-images.githubusercontent.com/29114032/223051071-c3e41475-0dc8-43a0-9ffe-d5d25c8e15db.gif)

**Comment by quanho** [comment]
This is the same as https://github.com/qlik-oss/sn-list-objects/issues/40.
