### ISSUE TITLE
Remove search glass

### ISSUE THREAD

**Issue by DanielS-Qlik** [qlik-oss/sn-list-objects#111]
When search option `false` is passed to the Listbox, the search glass should be hidden

**Comment by quanho** [comment]
Is this a part of https://github.com/qlik-oss/sn-list-objects/issues/72?

**Comment by quanho** [comment]
This is not an important issue for the new filter pane. This should be converted to a small improvement.

**Comment by veinfors** [comment]
solved in https://github.com/qlik-oss/nebula.js/pull/1141
