### ISSUE TITLE
Title in Sub-panel does not evaluate an expression

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#115]
I think the title of the dimension should have the evaluated expression?

See image
![Capture](https://user-images.githubusercontent.com/29114032/223691609-08d40e1f-51df-43d7-a83d-a1101a2aae2d.PNG)

**Comment by quanho** [comment]
In the map chart, there is overlay sub property panel and in there we do not use evaluated expression. So should we use it here.
