### ISSUE TITLE
Sub-panel should probably be closed as soon as you click somewhere outside of the object

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#118]
There can be some ugly result when you drag objects into the sheet while having the sub-panel open. Maybe it should be closed if you click outside of the FP in question?

See video:

![abc!](https://user-images.githubusercontent.com/29114032/224303200-243c99aa-1803-44f1-a846-7c3d7d04b74b.gif)

**Comment by quanho** [comment]
This should be fixed by https://github.com/qlik-trial/sense-client/pull/23510
