### ISSUE TITLE
Increase the size of the listbox popup

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#125]
When opening a collapsed FP the pooup is not as wide as the old. Same goes for multiple list items

New:
![Capture](https://user-images.githubusercontent.com/29114032/224666537-3d89878d-74c7-4cea-ad1d-4d3e2d2b5c84.PNG)
![Capture](https://user-images.githubusercontent.com/29114032/224667431-ae49a8b0-27d0-4a4d-9b3d-6d21c5a1b67a.PNG)

OLD:
![Capture](https://user-images.githubusercontent.com/29114032/224667065-72bbc154-d33a-404f-b71e-ace0f43d140e.PNG)

**Comment by veinfors** [comment]
Instead of rendering the listbox inside a popover like we do now, we should use the popoverlistbox that exists in nebula.js
