### ISSUE TITLE
Old APP: placement is different if I open app with or without FF

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#137]
APP:  [Qlik_DrillDown_Debugging.zip](https://github.com/qlik-oss/sn-list-objects/files/10968644/Qlik_DrillDown_Debugging.zip)

1: Open attached app with FF 
FP looks as below:
![Capture](https://user-images.githubusercontent.com/29114032/225004240-28c0a116-a395-417b-8df1-6a9746f7b164.PNG)

2: OPen attached app without FP (old FP)
FP looks like below:
![Capture](https://user-images.githubusercontent.com/29114032/225004402-0678df35-b0e9-4a5a-9ed6-f1bd0c3de004.PNG)

**Comment by DanielS-Qlik** [comment]
fix in: #154
