### ISSUE TITLE
Not possible to scroll to see all values in grid mode

### ISSUE THREAD

**Issue by johanlahti** [qlik-oss/sn-list-objects#144]
## Reproduce:

```
dataLayout: grid
layoutOrder: column
maxColumns: auto (this is always auto in sense-client)
maxRows: 100000… (has to be higher than nbr of items in the field)
```

## Result:

The listbox cannot be scrolled (note that for the "column" case, the scroll should appear on the X-axis, because of `overflow-x: 'auto'`). This happens because it's overflowing the y-axis (the rows are just continuing) instead of adding enough columns to host the values.

![image](https://user-images.githubusercontent.com/5780544/225305927-fd3543d1-ce45-4667-aa88-66b5afc62ba5.png)

## Expected result:

The listbox should not overflow the y-axis but instead add enough columns to host all values (thus adding scroll).

**Comment by T-Wizard** [comment]
I think this is the same problem as #146
and the same type of problem as #127
