### ISSUE TITLE
If selection is confirmed in a collapsed FP then the popup should be closed

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#160]
1: Make sure you have a collapsed filterpane
2: Make a selection
3: Confirm selection or cancel selection
Popup with field should close down

See new:
![abc!](https://user-images.githubusercontent.com/29114032/225829774-8d22e166-c49e-49ab-b728-91665dd96eac.gif)

See old:
![abc!](https://user-images.githubusercontent.com/29114032/225830064-9b44d05b-f34d-447e-90ee-9f1d1b5d4dd1.gif)

**Comment by T-Wizard** [comment]
To match old filter pane. it should only close if the dimension is not a drilldown dimension
