### ISSUE TITLE
Listboxes are transparent when used as native chart

### ISSUE THREAD

**Issue by johanlahti** [qlik-oss/sn-list-objects#20]
In sense-client:

![image](https://user-images.githubusercontent.com/5780544/200308282-5c3fd2a4-2cdb-4a25-a646-5fef1f8ff47d.png)

We need to add a background color in nebula or sn-filter-pane. Note that we want the space in-between collapsed Listboxes to remain transparent/grey.

**Comment by DanielS-Qlik** [comment]
Background color has been added in this PR: https://github.com/qlik-oss/nebula.js/pull/1022
