### ISSUE TITLE
Improvement: Distinguish which dimension/field has the sub-panel open

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#209]
1: Create a few dimensions in a Filterpanel
2: Open the subpanel 
It is a bit hard to see which dimension has the sub-panel open, Both colorwise and maybe an arrow or something.

![image (3)](https://user-images.githubusercontent.com/29114032/227212802-a16a6261-8bb9-4484-9df0-643b04367b52.png)

**Comment by luckehal** [comment]
It has happened more than once that I click on the already selected data field thus closing the sub-panel because of the small difference btween selected and not selected

**Comment by luckehal** [comment]
Making selected button text bold and/or italic could be another way to help distinguish selected data field

**Comment by pernyl** [comment]
After discussing with UX the descision was to close this now since the change is just to big. Might take a second look at this in the future, But closing for now

**Comment by johanlahti** [comment]
I see one tiny improvement we could make to highlight the active state. In the charts section they use a slightly darker border color: `rgba(0, 0, 0, 0.5)`. It's a small change but I think it makes quite a bit of a difference, see below:

Now:
<img width="245" alt="image" src="https://github.com/qlik-oss/sn-list-objects/assets/5780544/46b1ff7b-aae5-4396-a358-7517f07d3503">


After making darker:
<img width="245" alt="image" src="https://github.com/qlik-oss/sn-list-objects/assets/5780544/ef9d2fd9-aba7-4447-9125-6c28f00b3a5e">

**Comment by pernyl** [comment]
@johanlahti Maybe you can send the suggestion to martin Chakirov?

**Comment by johanlahti** [comment]
I think it's small enough to just change it, since it's also consistent with the other section. I will put up a PR.
