### ISSUE TITLE
Enter get stuck after a collaped filter pane is out of focus

### ISSUE THREAD

**Issue by quanho** [qlik-oss/sn-list-objects#254]
Pressing enter does not go from a filter pane to a collapsed listbox after the filter pane is out of focus (by clicking a mouse outside the web browser) and get back to focus (by clicking back inside the browser and press tab few times to focus back on that filter pane).
![Screenshot 2023-04-05 at 09 58 00](https://user-images.githubusercontent.com/20044781/230018115-1158d8ae-75a5-42cd-8309-308c758726db.png)

**Comment by pernyl** [comment]
@quanho Is this fix that if I press Enter and go into a FP then I go back out with for example Shift+tab. THen I move around and get back to the same FP ant then Enter does not work?
