### ISSUE TITLE
"Enter" does not work as expected in collapsed filterpane

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#263]
1: Tab to a collapsed listbox
2: Press Enter - listbox popover is opened
3: Press enter again 
Expected: I would like to have focus on the first item of the list - actually already after step 2 focus should be on first item
Actual: I end up in the selection menu and will never come to the items in the list with enter

See movie:

![abc!](https://user-images.githubusercontent.com/29114032/231437313-cbe82a48-627d-4e53-bc26-fa3682e0e996.gif)

**Comment by quanho** [comment]
In the old filter pane there is search box and on enter we focus on search box and then we need to tab to jump to the first row. In the new filter pane we do not open search box as default so on enter we focus on the popover and then we tab to jump to the first row.

**Comment by pernyl** [comment]
@quanho But it is very strange that if you want to come to the first item of a filterpane you have to use different keyboards button depending on if it is a collapsed or not.

Not collapsed from sheet:
1: "tab" to object
2: "Enter" to go inside object
3: Arrow keys to move to the listbox you want to enter
**4: "Enter" to go to the first item of listbox**

Collapsed from sheet 
1: "tab" to object
2: "Enter" to go inside object
3: Arrow keys to move to the collapsed listbox you want to enter
4: "Enter" again to open popover
**5: "tab" to go to the first item of listbox**

**Comment by quanho** [comment]
We will support Enter -> Enter which should work like Enter -> Tab
