### ISSUE TITLE
Focus lost efter tabbing from FP on sheet

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#274]
1: Tab to sheet and FP
2: Tab once more
Notice that focus is lost and you don't really know where you are. Tabbing forward doesn't help neither does shift+tab to go back

If I do the same with any other object I get focus on Chromes "Search tabs" - see image:

![Capture](https://user-images.githubusercontent.com/29114032/232467342-19186b58-ddd3-442f-9ddb-5720dd5a7912.PNG)

**Comment by pernyl** [comment]
Still seen with client version 7.962

**Comment by quanho** [comment]
I tested https://hva.eu.hva.pte.qlikdev.com/ on my window machine and couldn't find the problem
![Ctrl-00 - Navigation 1 _ Sheet - Qlik Sense - Google Chrome 2023-04-24 15-56-20](https://user-images.githubusercontent.com/20044781/234020265-6da81f5d-8566-45e3-adf1-4338540c8d16.gif)

**Comment by pernyl** [comment]
I will close the issue for now
