### ISSUE TITLE
Unresponsive after selection (Performance)

### ISSUE THREAD

**Issue by DanielS-Qlik** [qlik-oss/sn-list-objects#40]
After making a selection the list gets unresponsive for about 300-400ms depending on the visible size of the list.
![Kapture 2022-12-16 at 08 39 16](https://user-images.githubusercontent.com/99665802/208048417-8f2b9991-0977-46b7-a625-a2fecc5fd1a2.gif)

**Comment by quanho** [comment]
This is the same as https://github.com/qlik-oss/sn-list-objects/issues/105.
