### ISSUE TITLE
Blank background when no data in sense-client

### ISSUE THREAD

**Issue by DanielS-Qlik** [qlik-oss/sn-list-objects#48]
New:
![Screenshot 2023-02-15 at 15 09 20](https://user-images.githubusercontent.com/99665802/219051049-6fbb855a-f706-44fa-a890-f7a3dd9b41c7.png)

Old:
![Screenshot 2023-02-15 at 15 09 53](https://user-images.githubusercontent.com/99665802/219051054-d007b4e5-e264-4b61-a3bc-c36a73f91c86.png)

**Comment by quanho** [comment]
Should be fixed by https://github.com/qlik-oss/sn-list-objects/pull/87
