### ISSUE TITLE
Scroll is always seen

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#55]
In the old FP the scroll is only seen when hovering on the dimension.

See video:
New FP:
![abc!](https://user-images.githubusercontent.com/29114032/222055264-659d97f9-d898-472f-bcf0-1b54d3c90623.gif)
Old FP:
![abc!](https://user-images.githubusercontent.com/29114032/222055467-7240ca22-95bb-40fc-ac05-ec25405d0c45.gif)

**Comment by quanho** [comment]
This is a very big task and we need to do it for all nebula charts like sn-table. I will convert this to an improvement.

**Comment by afridell** [comment]
I think we can close this since we have PM decision on keeping the always visible scrollbars
