### ISSUE TITLE
There is no truncation on titles

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#58]
See images
![Capture](https://user-images.githubusercontent.com/29114032/222057969-9b0fa46b-bafb-4ca9-bf2e-a7bb197c96a4.PNG)

![Capture](https://user-images.githubusercontent.com/29114032/222058077-fd95e9a2-0885-485d-b65a-8bf7ae8b93f5.PNG)

**Comment by DanielS-Qlik** [comment]
For Listbox: https://github.com/qlik-oss/nebula.js/pull/1109

**Comment by johanlahti** [comment]
Can we close this? @DanielS-Qlik
