### ISSUE TITLE
Should the "search" button be highlighted in blue?

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#60]
1: Click search 
It is highlighted in a blue boarder and grey color - Should the blue boarder really be there?
2: Click search again to remove it
It is still highlighted with blue booarder and only way to remove it is to click somewhere else 

(other buttons are highlighted with a grey color and is grey when toggled and not grey when not toggled and of course when hovered it is also grey)

![abc!](https://user-images.githubusercontent.com/29114032/222059836-03f09332-8290-4e7e-9c6e-1679e52d2446.gif)

**Comment by CostInCode** [comment]
In the ActionToolbar, where we have other buttons of the same type (Mui IconButton) we get the same blue outline when clicked. We need to decide yet whether to remove this blue outline when clicking the buttons or having only when focusing on the button by keyboard navigation
<img width="663" alt="Screenshot 2023-03-02 at 14 09 04" src="https://user-images.githubusercontent.com/13185716/222438362-d60e1959-f19c-4bb6-af4c-6051defb6a34.png">

**Comment by T-Wizard** [comment]
maybe look if we can use [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
