### ISSUE TITLE
Extra space to the left of a number dimension

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#61]
See images:

New FP:
![Capture](https://user-images.githubusercontent.com/29114032/222060910-f057d179-6418-4649-817d-89f69779e536.PNG)
Old FP:
![Capture](https://user-images.githubusercontent.com/29114032/222061100-ecd36638-5880-4edf-b025-28927ac30fac.PNG)

**Comment by quanho** [comment]
This is fixed and now we reserve 24px for the tick.
In old filter pane we reserve 16 + 6(for right padding) = 22px for the tick but the tick is close to the text (to the left) than to the right edge, so it does not look nice like the new filter pane.
I will close this.
