### ISSUE TITLE
There are no tooltips on titles

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#65]
![abc!](https://user-images.githubusercontent.com/29114032/222067808-f9be9f6a-49f7-4cb0-b1f2-82ee82c0049b.gif)

**Comment by T-Wizard** [comment]
the colapsed listboxes do have tooltip (but with a long delay, maybe it should be shorter)

**Comment by T-Wizard** [comment]
tooltip for expanded listboxes fixed.
