### ISSUE TITLE
An extra boarder appears after selection around 3/4 of the FP

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#69]
See movie:

![abc!](https://user-images.githubusercontent.com/29114032/222090413-e70934d4-3273-4347-86a7-236fa0bb853e.gif)

**Comment by johanlahti** [comment]
Need to verify is this is solved by https://github.com/qlik-oss/nebula.js/pull/1125 or not

**Comment by johanlahti** [comment]
@pernyl Can you see (when the code is updated on the tenant) if this has been resolved. I can't see it in Chrome Mac.

https://user-images.githubusercontent.com/5780544/224491888-5b723a7a-c78d-43aa-a201-7c6aac94fdfe.mov
