### ISSUE TITLE
Searching with wildcard adds spaces into the search result

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#70]
See image:

![Capture](https://user-images.githubusercontent.com/29114032/222099577-043b14ab-aa84-4af5-8caa-a64f766bc748.PNG)

**Comment by johanlahti** [comment]
The algorithm is correct, something's up with the rendering.

**Comment by johanlahti** [comment]
The issue was that the component's `key` was not reflecting that it had changed, so it was not re-rendering when it should have.
