### ISSUE TITLE
Master item button is misaligned and should be "bold"

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#77]
1: Open sub-panel and look at the button for master item. See image and see that the text is not centered (same for edit)
The text should also be **bold** inside the button

![Capture](https://user-images.githubusercontent.com/29114032/222148410-0f24a3bb-f217-4934-ba12-fb245d3c5c15.PNG)

**Comment by johanlahti** [comment]
![image](https://user-images.githubusercontent.com/5780544/224346539-ce4455b9-fa78-4c0f-a1df-5fc33d42a8c3.png)
