### ISSUE TITLE
Set focus with keyboard in sense

### ISSUE THREAD

**Issue by DanielS-Qlik** [qlik-oss/sn-list-objects#81]
You should be able to enter "table representation"-mode when pressing enter on a filterpane.

Old:
![Kapture 2023-03-02 at 09 34 37](https://user-images.githubusercontent.com/99665802/222375900-12a72359-afa4-4e0d-974c-09b16a019542.gif)

New:
![Kapture 2023-03-02 at 09 32 47](https://user-images.githubusercontent.com/99665802/222375981-35ff3831-c6de-482a-8e54-fb5133374dc2.gif)

**Comment by pernyl** [comment]
Might be related to #67 since the context menu doesn't show the correct things and not all things are working in it.
