### ISSUE TITLE
Translation: Some strings are not translated but hardcoded

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#84]
Searching for an item that does not exist gives you this error message: **There are no matches for your search.** 

The text "Search in listbox" in search

The tooltip when hovering on the search icon "search in listbox"

Scrolling in a large listobject and you exceed the amount you get the following message: **Currently showing a limited data set, use search to reduce the data.** 

In QCS you can use the url /language/qps-ploc/ to see if it is translateable or not.

![Capture](https://user-images.githubusercontent.com/29114032/222398600-946944df-7773-4cf6-a5ee-83dd4f56e79e.PNG)

**Comment by johanlahti** [comment]
This has been resolved. For the records, the string was never hard-coded but previously we did not send the language code from sense-client to nebula, and this has been changed now.
