### ISSUE TITLE
When checkbox mode is used frequency count is too close to the data

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#85]
1: Use a number field
2: Enable frequency count
3: Enable checkbox mode
Notice that frequency count and data is too close

See movie
![abc!](https://user-images.githubusercontent.com/29114032/222405245-cdd53c96-875b-423c-9a4b-29c044885504.gif)

**Comment by johanlahti** [comment]
This should be fixed now.
