### ISSUE TITLE
Listbox should not collapse when small size

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#89]
If you have only one dimension then this should not collapse when small mode in grid mode.

See video:

![abc!](https://user-images.githubusercontent.com/29114032/222648339-c43c1e2e-5387-45b5-bc2a-eca46eaaa470.gif)

**Comment by johanlahti** [comment]
I assigned this to you @DanielS-Qlik as I think you know this implementation best.
